# Generated by Django 2.0.13 on 2019-02-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hab_level', models.CharField(choices=[('0', 'None'), ('1', 'Hab Level 1'), ('2', 'Hab Level 2'), ('3', 'Hab Level 3')], max_length=1)),
                ('speed', models.IntegerField(default=0)),
                ('strategy', models.IntegerField(default=0)),
                ('team_work', models.IntegerField(default=0)),
                ('recommend', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cargo', 'Picked up Cargo'), ('hatch', 'Picked up Hatch'), ('hatch2rocket', 'Secured Hatch Rocket'), ('cargo2rocket', 'Secured Cargo Rocket'), ('hatch2ship', 'Secured Hatch Cargo Ship'), ('cargo2ship', 'Secured Cargo Cargo Ship')], max_length=16)),
                ('seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scouter', models.CharField(max_length=45)),
                ('match_number', models.IntegerField()),
                ('event_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['match_number'],
            },
        ),
        migrations.CreateModel(
            name='PitScout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('recommend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_number', models.IntegerField(default=0)),
                ('team_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='pitscout',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout.Robot'),
        ),
        migrations.AddField(
            model_name='match',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout.Robot'),
        ),
        migrations.AddField(
            model_name='ingame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_game_actions', to='scout.Match'),
        ),
        migrations.AddField(
            model_name='endgame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_game', to='scout.Match'),
        ),
    ]
