# Generated by Django 2.0.13 on 2019-02-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
