# Generated by Django 2.0.13 on 2019-02-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0002_robot_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endgame',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='end_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scout.EndGame'),
        ),
    ]
