# Generated by Django 2.0.13 on 2019-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_auto_20190223_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='alliance',
            field=models.CharField(default='b', max_length=1),
        ),
    ]
