# Generated by Django 2.0.13 on 2019-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0004_match_alliance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitscout',
            old_name='recommend',
            new_name='do_not_pick',
        ),
        migrations.AddField(
            model_name='pitscout',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
