# Generated by Django 2.0.13 on 2019-02-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0005_auto_20190223_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachScout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synergy', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('week_number', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='start_position',
            field=models.CharField(choices=[('1', 'Hab Level 1'), ('2', 'Hab Level 2')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='coachscout',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout.Match'),
        ),
        migrations.AddField(
            model_name='coachscout',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout.Robot'),
        ),
    ]
