# Generated by Django 2.0.13 on 2019-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0006_auto_20190223_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitscout',
            name='cargo_in_sandstorm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='cargo_in_teleop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='climb_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='favorite_feature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='ground_pickup_cargo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='ground_pickup_hatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='hatches_in_sandstorm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='hatches_in_teleop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='max_rocket_height',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='snow_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscout',
            name='starts_on_hab_2',
            field=models.BooleanField(default=False),
        ),
    ]
