# Generated by Django 2.0.13 on 2019-02-23 17:24

from django.db import migrations, models
import django.db.models.deletion
import scout.models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0007_auto_20190223_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachscout',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scout.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_key',
            field=models.CharField(default=scout.models.random_words, max_length=55),
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scout.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitscout',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scout.Event'),
            preserve_default=False,
        ),
    ]
