# Generated by Django 2.0.13 on 2019-03-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0009_event_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachscout',
            name='scouter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
