# Generated by Django 2.0.13 on 2019-03-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0011_pitscout_scouter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='MatchScout',
        ),
    ]
