# Generated by Django 2.0.13 on 2019-03-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0016_auto_20190308_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitscout',
            name='buddy_climb',
            field=models.BooleanField(default=False),
        ),
    ]
