# Generated by Django 2.0.13 on 2019-03-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0017_pitscout_buddy_climb'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscout',
            name='hab_level_int',
            field=models.IntegerField(default=0),
        ),
    ]
