# Generated by Django 2.0.13 on 2019-03-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0018_matchscout_hab_level_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='robot_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
